import { StyleSheet } from 'react-native';

export const forcaStyles = StyleSheet.create({
  scrollContent: {
    flexGrow: 1,
    padding: 20,
    backgroundColor: '#e9eef2',
    alignItems: 'center',
  },
  card: {
    width: '100%',
    maxWidth: 980,
    backgroundColor: '#ffffff',
    borderRadius: 18,
    padding: 24,
    borderWidth: 1,
    borderColor: '#eef2f7',
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  header: {
    marginBottom: 16,
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: '700',
    marginBottom: 6,
    letterSpacing: 0.5,
  },
  subtitle: {
    color: '#5b6b7a',
    fontSize: 16,
  },
  stage: {
    flexDirection: 'column',
    gap: 16,
  },
  stageWide: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 24,
  },
  infoPanel: {
    flex: 1,
    gap: 16,
  },
  label: {
    fontSize: 14,
    color: '#6b7a8a',
    marginBottom: 4,
  },
  pill: {
    alignSelf: 'flex-start',
    paddingVertical: 6,
    paddingHorizontal: 14,
    backgroundColor: '#f0f7ff',
    color: '#0b63ce',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#cfe3ff',
    fontWeight: '700',
    fontSize: 16,
    textAlign: 'center',
  },
  word: {
    fontFamily: 'monospace',
    letterSpacing: 8,
    fontSize: 26,
    backgroundColor: '#0b1b2a',
    color: '#e6f2ff',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#122a40',
  },
  inputRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginVertical: 18,
  },
  textInput: {
    flexGrow: 1,
    minWidth: 120,
    height: 48,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#cfd8e3',
    paddingHorizontal: 14,
    fontSize: 18,
    backgroundColor: '#fff',
  },
  primaryButton: {
    height: 48,
    paddingHorizontal: 16,
    borderRadius: 10,
    backgroundColor: '#1363d1',
    justifyContent: 'center',
    alignItems: 'center',
  },
  primaryButtonText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 16,
  },
  secondaryButton: {
    height: 48,
    paddingHorizontal: 16,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#cfd8e3',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
  },
  secondaryButtonText: {
    color: '#1f2d3a',
    fontWeight: '600',
    fontSize: 16,
  },
  keyboard: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 16,
  },
  key: {
    width: '7%',
    minWidth: 38,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#d9e2ec',
    backgroundColor: '#f8fafc',
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  keyDisabled: {
    backgroundColor: '#eef2f7',
    borderColor: '#d9e2ec',
  },
  keyText: {
    fontWeight: '600',
    color: '#1f2d3a',
    fontSize: 14,
  },
  keyTextDisabled: {
    color: '#9aa7b5',
  },
  attempts: {
    flexDirection: 'column',
    gap: 12,
  },
  attemptsWide: {
    flexDirection: 'row',
    gap: 16,
  },
  chipsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    alignItems: 'center',
  },
  chip: {
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 999,
    fontSize: 14,
    borderWidth: 1,
  },
  chipGreen: {
    backgroundColor: '#e6f8ee',
    borderColor: '#bdeccd',
    color: '#136f3a',
  },
  chipRed: {
    backgroundColor: '#ffecec',
    borderColor: '#ffc9c9',
    color: '#a61b1b',
  },
  chipMuted: {
    color: '#98a6b5',
  },
  result: {
    marginTop: 18,
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
  },
  victory: {
    backgroundColor: '#e9f8ff',
    borderColor: '#bfe8ff',
    color: '#0a577a',
  },
  defeat: {
    backgroundColor: '#fff2f2',
    borderColor: '#ffd9d9',
    color: '#8f1a1a',
  },
  resultTitle: {
    fontSize: 20,
    fontWeight: '700',
    marginBottom: 4,
  },
  resultText: {
    fontSize: 16,
  },
});
